swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transaction:
    get:
      security:
        - Bearer: []
      tags:
        - User transaction
      summary: List all user transaction id
      description: API for fetching all user transaction id
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: List all user transaction retrieved successully
          schema:
            $ref: '#/definitions/Transaction-minify'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - User transaction
      summary: Create new transaction
      description: API to create new user transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/Transaction-one-post'
      produces:
        - application/json
      responses:
        '200':
          description: New transaction retrieved successully
          schema:
            $ref: '#/definitions/Transaction-one-post-receive'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transaction/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - User transaction
      summary: Get one entry from API
      description: Get one entry from API
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path 
          type: number
          name: transactionId
          description: transaction id
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User transaction information retrieved successully
          schema:
            $ref: '#/definitions/Transaction-one'
        '400':
          description: Invalid Fields
        '404':
          description: Invalid ID
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User transaction
      summary: Updating one entry from API
      description: Updating one entry from API
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path 
          type: number
          name: transactionId
          description: transaction id
          required: true
        - in: body
          name: body
          description: Update user transaction attributes
          required: true
          schema:
            $ref: '#/definitions/Transaction-modification'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction information retrieved successully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '404':
          description: Invalid ID
        '500':
          description: Internal Server Error
  /user/transaction/month:
    get:
      security:
        - Bearer: []
      tags:
        - User transaction
      summary: API for fetching a user transaction for current month
      description: API for fetching a user transaction for current month
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User transaction for current month retrieved successully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  Transaction:
    type: array
    items:
      properties:
        id:
          type: string
        current-balance:
          type: number
        transaction-date:
          type: string
          format: date-time
        transaction-description:
          type: string
        transaction-amount:
          type: number
        transaction-type:
          type: string
        transaction-category:
          type: string
        transaction-notes:
          type: string
  Transaction-minify:
    type: array
    items:
      properties:
        id:
          type: string
        transaction-date:
          type: string
          format: date-time
  Transaction-one:
    type: object
    properties:
      id:
        type: string
      current-balance:
        type: number
      transaction-date:
        type: string
        format: date-time
      transaction-description:
        type: string
      transaction-amount:
        type: number
      transaction-type:
        type: string
      transaction-category:
        type: string
      transaction-notes:
        type: string
  Transaction-one-post:
    type: object
    properties:
      transaction-description:
        type: string
      transaction-amount:
        type: number
      transaction-type:
        type: string
      transaction-category:
        type: string
      transaction-notes:
        type: string
  Transaction-one-post-receive:
    type: object
    properties:
      id:
        type: string
      last-balance:
        type: number
      new-balance:
        type: number
      transaction-date:
        type: string
        format: date-time
      transaction-description:
        type: string
      transaction-amount:
        type: number
      transaction-type:
        type: string
      transaction-category:
        type: string
      transaction-notes:
        type: string
  Transaction-modification:
    type: object
    properties:
      transaction-type:
        type: string
      transaction-category:
        type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
